dataset: celeba

model_params:
  name: 'Condition_VAE_Conv'
  num_channels: 3
  img_size: 64
  latent_dim: 40
  num_classes: 5
  hidden_size: 1536
  cur_device: 'cuda'
  pretrained: True

data_params_aug:
  data_path: "path of celeba data!!!"
  train_batch_size: 128
  val_batch_size: 200
  num_workers: 4
  pin_memory: True
  image_size: 64
  aug_way: cvae

exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 1
  manual_seed: 1000


trainer_params:
  gpus: [0]
  max_epochs: 90

logging_params:
  save_dir: "logs/Classifcation/"
  name: "OCVAE_celeba"