dataset: celeba

data_params_aug:
  data_path: "path of celeba data!!!"
  train_batch_size: 128
  val_batch_size: 200
  num_workers: 4
  pin_memory: True
  image_size: 64
  aug_way: rs

trainer_params:
  gpus: [0]
  max_epochs: 90

exp_params:
  manual_seed: 1000
  
logging_params:
  save_dir: "logs/Classifcation/"
  name: "RS_celeba"