dataset: mnist

model_params:
  name: 'MGVAE_MLP'
  latent_dim: 10
  hiddden_size: 300
  number_components: 10000
  cur_device: 'cuda'
  pretrained: True

data_params_aug:
  data_path: "path of mnist!!!"
  train_batch_size: 100
  val_batch_size: 100
  patch_size: 64
  num_workers: 4
  target_label: [0,1,2,3,4,5,6,7,8,9]
  # downsample_size: [0,0,0,0,0,10,10,10,10,10]
  downsample_size: [0,0,0,0,0,60,60,60,60,60]
  aug_way: etg

data_params_majority:
  data_path: "path of mnist!!!"
  train_batch_size: 100
  val_batch_size: 100
  patch_size: 64
  num_workers: 4
  target_label: [0,1,2,3,4]
  downsample_size: [0,0,0,0,0]

trainer_params:
  gpus: [0]
  max_epochs: 100

exp_params:
  manual_seed: 1265
  
logging_params:
  save_dir: "logs/Classifcation/"
  name: "MGVAE_mnist"