dataset: mnist

model_params:
  name: 'Condition_VAE_MLP'
  num_channels: 1
  img_size: 28
  latent_dim: 40
  num_classes: 2
  hidden_size: 300
  cur_device: 'cuda'
  pretrained: True

data_params_aug:
  data_path: "path of mnist!!!"
  train_batch_size: 100
  val_batch_size: 100
  num_workers: 4
  pin_memory: True
  target_label: [0,1,2,3,4,5,6,7,8,9]
  downsample_size: [0,0,0,0,0,10,10,10,10,10]
  aug_way: cvae

exp_params:
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 90

logging_params:
  save_dir: "logs/Classifcation/"
  name: "OCVAE_mnist"