dataset: celeba

model_params:
  name: 'MGVAE_Conv'
  latent_dim: 40
  hidden_size: 1536
  number_components: 5000
  cur_device: 'cuda'
  pretrained: False

data_params_majority:
  data_path: "path of majority celeba data!!!"
  train_batch_size: 100
  val_batch_size: 100
  num_workers: 4
  image_size: 64


data_params_minority:
  data_path: "path of minority celeba data!!!"
  train_batch_size: 100
  val_batch_size: 100
  num_workers: 4
  image_size: 64


exp_params:
  LR: 0.0005
  weight_decay: 0.0
  # scheduler_gamma: 0.95
  kld_weight: 1
  manual_seed: 1265

ewc_params:
  ewc: False
  ewc_weight: 50

trainer_params:
  gpus: [0]
  max_epochs: 200

logging_params:
  save_dir: "logs/Oversampling_Model/"
  name: "MGVAE_Celeba"
