dataset: celeba

model_params:
  name: 'Condition_VAE_Conv'
  num_channels: 3
  img_size: 64
  latent_dim: 40
  num_classes: 5
  hidden_size: 1536
  cur_device: 'cuda'
  pretrained: False

data_params:
  data_path: "/home/qingzhong/data/celeba/celeba_hair_longtail"
  train_batch_size: 100
  val_batch_size: 100
  num_workers: 4
  pin_memory: True
  image_size: 64
  aug_way: erm

exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 1
  manual_seed: 1265


trainer_params:
  gpus: [0]
  max_epochs: 200

logging_params:
  save_dir: "logs/Oversampling_Model/"
  name: "OCVAE_Celeba"
